name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install pylint
        
    - name: Get non-empty Python files
      id: get_py_files
      run: |
        # Use find to list all non-empty .py files and store them
        py_files=$(find . -name "*.py" -size +0c)
        echo "files=$py_files" >> $GITHUB_OUTPUT
   
    - name: Run Pylint on non-empty files
      if: ${{ steps.get_py_files.outputs.files != '' }}
      run: |
        pylint ${{ steps.get_py_files.outputs.files }}
        
